# -*- coding: utf-8 -*-
"""AI_Internship Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwrEw_vMWK8kKS4t0dhYRUxLlikrpB30
"""

pip install moviepy gtts pillow

import os
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import ImageSequenceClip, AudioFileClip
from gtts import gTTS

# Create output folders
os.makedirs("frames", exist_ok=True)
os.makedirs("videos", exist_ok=True)

def create_equation_video(equation_steps, final_equation, video_name, voice_text=None):
    # Generate frames
    frame_paths = []
    for i, step in enumerate(equation_steps):
        img = Image.new("RGB", (640, 480), (255, 255, 255))
        draw = ImageDraw.Draw(img)

        try:
            font = ImageFont.truetype("arial.ttf", 60)
        except:
            font = ImageFont.load_default()

        # Updated code to replace deprecated textsize()
        bbox = draw.textbbox((0, 0), step, font=font)
        w = bbox[2] - bbox[0]
        h = bbox[3] - bbox[1]

        draw.text(((640 - w) / 2, (480 - h) / 2), step, fill="black", font=font)

        frame_path = f"frames/{video_name}_frame_{i}.png"
        img.save(frame_path)
        frame_paths.append(frame_path)

    # Create video clip from frames
    clip = ImageSequenceClip(frame_paths, fps=1)

    # Add voiceover (optional)
    if voice_text:
        tts = gTTS(voice_text)
        audio_path = f"videos/{video_name}_audio.mp3"
        tts.save(audio_path)
        audio = AudioFileClip(audio_path)
        clip = clip.set_audio(audio)

    # Export video
    output_path = f"videos/{video_name}.mp4"
    clip.write_videofile(output_path, fps=1)


# 1. Addition Video
create_equation_video(
    equation_steps=["1", "1 +", "1 + 2", "1 + 2 =", "1 + 2 = 3"],
    final_equation="1 + 2 = 3",
    video_name="add",
    voice_text="One plus two equals three"
)

# 2. Subtraction Video
create_equation_video(
    equation_steps=["5", "5 -", "5 - 3", "5 - 3 =", "5 - 3 = 2"],
    final_equation="5 - 3 = 2",
    video_name="sub",
    voice_text="Five minus three equals two"
)

# 3. Multiplication Video
create_equation_video(
    equation_steps=["9 × 8 =", "9 × 8 = 72"],
    final_equation="9 × 8 = 72",
    video_name="mul",
    voice_text="Nine times eight equals seventy-two"
)